version: "3"

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=nbclassic

  opensearch:
    image: opensearchproject/opensearch:2.2.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
       - discovery.type=single-node

